const cron = require('node-cron');
const prisma = require('../config/db');
const { nowBD, todayWorkDateBD } = require('../utils/dateUtils');
const timeService = require('./timeService');

// Runs every minute — checks every currently IN_OFFICE employee against
// their auto-checkout deadline: (remaining target hours + 4hr buffer)
// from when their current IN_OFFICE interval began (Spec §4).
async function checkAndAutoCheckout() {
  const workDate = todayWorkDateBD();
  const settings = await prisma.globalSettings.findUnique({ where: { id: 1 } });
  const bufferHours = settings?.autoCheckoutBufferHours ?? 4;

  const employees = await prisma.employee.findMany({ where: { active: true } });

  for (const emp of employees) {
    const { state, lastEvent } = await timeService.getCurrentState(emp.id);
    if (state !== 'IN_OFFICE') continue; // only running sessions can overrun

    const targetHours = settings?.dailyTargetHours ?? 8;
    const workedSecondsSoFar = await timeService.getWorkedSecondsToday(emp.id);
    const remainingHours = Math.max(0, targetHours - workedSecondsSoFar / 3600);
    const allowedMs = (remainingHours + bufferHours) * 3600000;

    const sessionStartedAt = new Date(lastEvent.serverTimestamp); // CHECK_IN or BREAK_END
    const elapsedMs = nowBD().getTime() - sessionStartedAt.getTime();

    if (elapsedMs >= allowedMs) {
      await prisma.attendanceEvent.create({
        data: {
          employeeId: emp.id,
          type: 'CHECK_OUT',
          isAutoGenerated: true,
          isForgotFlag: true,
          workDate,
          serverTimestamp: nowBD(),
        },
      });
      console.log(`[autoCheckoutJob] auto-checked-out ${emp.name} (forgot to check out)`);
    }
  }
}

function start() {
  // Every minute — auto-checkout deadlines need minute-level precision,
  // not hour-level, since the buffer window can end at any time of day.
  cron.schedule('* * * * *', () => {
    checkAndAutoCheckout().catch(err => console.error('[autoCheckoutJob] error:', err));
  });
  console.log('[autoCheckoutJob] scheduled (every minute)');
}

module.exports = { start };